theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Md Mursalin Islam
description: md.islam@uni-a.de
logo: /assets/img/logo.png
# Hide GitHub footer links
show_downloads: true
github:
  is_project_page: false
